export const START_WEEK_1 = 'START_WEEK_1';
export const CURRENT_SEMESTER = 'CURRENT_SEMESTER';
export const START_REGISTER_CLASS_OFFICIAL_STANDARD = 'START_REGISTER_CLASS_OFFICIAL_STANDARD';
export const START_REGISTER_CLASS_UNOFFICIAL_STANDARD = 'START_REGISTER_CLASS_UNOFFICIAL_STANDARD';
export const START_REGISTER_CLASS_OFFICIAL_ELITECH = 'START_REGISTER_CLASS_OFFICIAL_ELITECH';
export const START_REGISTER_CLASS_UNOFFICIAL_ELITECH = 'START_REGISTER_CLASS_UNOFFICIAL_ELITECH';
export const START_REGISTER_FREE = 'START_REGISTER_FREE';

export const END_REGISTER_CLASS_OFFICIAL_STANDARD = 'END_REGISTER_CLASS_OFFICIAL_STANDARD';
export const END_REGISTER_CLASS_UNOFFICIAL_STANDARD = 'END_REGISTER_CLASS_UNOFFICIAL_STANDARD';
export const END_REGISTER_CLASS_OFFICIAL_ELITECH = 'END_REGISTER_CLASS_OFFICIAL_ELITECH';
export const END_REGISTER_CLASS_UNOFFICIAL_ELITECH = 'END_REGISTER_CLASS_UNOFFICIAL_ELITECH';
export const END_REGISTER_FREE = 'END_REGISTER_FREE';

export const START_REGISTER_COURSE = 'START_REGISTER_COURSE';
export const END_REGISTER_COURSE = 'END_REGISTER_COURSE';
